"""empty message

Revision ID: d8446ff31bb2
Revises: 4edfe2343135
Create Date: 2026-02-11 21:56:30.099212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8446ff31bb2'
down_revision = '4edfe2343135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower', sa.Integer(), nullable=False),
    sa.Column('follow_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follow_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower', 'follow_by')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
